name="voice-notes-pages"
compatibility_date="2022-07-12"

workers_dev = false


[[d1_databases]]
binding = "DB"
database_name = "voice-notes-dev"
database_id = "0926c8a1-cca7-444b-b2be-209b07ae2a04"
migrations_dir="drizzle"
